[build-system]
requires = [
    "hatchling>=1.25.0",
    "hatch-vcs>=0.4.0",
]
build-backend = "hatchling.build"

[project]
name = "uarite"
dynamic = ["version"]
description = "User-Agent parsing done right. Accurate, small, pure Python and fast."
authors = [
    { name = "Leo Vasanko" },
]
keywords = ["user-agent", "ua-parser"]
readme = "README.md"
license = "MIT OR Unlicense"
requires-python = ">=3.10"
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
]
dependencies = []

[project.urls]
Repository = "https://git.zi.fi/LeoVasanko/uarite"
Issues = "https://github.com/LeoVasanko/uarite"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["uarite"]
